cloud:
  aws:
    credentials:
      accessKey: AKIAYYR57WZ7ITAVHBNE
      secretKey: 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
    s3:
      bucket: maru-event-image
    region:
      static: ap-northeast-2
    stack:
      auto: false